/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IncomingRouteImport } from './routes/incoming'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OutgoingRouteImport } from './routes/outgoing'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockMovementsRouteImport } from './routes/stock-movements'
import { Route as SuppliersRouteImport } from './routes/suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingRoute = IncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OutgoingRoute = OutgoingRouteImport.update({
  id: '/outgoing',
  path: '/outgoing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockMovementsRoute = StockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/incoming': typeof IncomingRoute
  '/inventory': typeof InventoryRoute
  '/outgoing': typeof OutgoingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/incoming': typeof IncomingRoute
  '/inventory': typeof InventoryRoute
  '/outgoing': typeof OutgoingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/incoming': typeof IncomingRoute
  '/inventory': typeof InventoryRoute
  '/outgoing': typeof OutgoingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/incoming'
    | '/inventory'
    | '/outgoing'
    | '/reports'
    | '/settings'
    | '/stock-movements'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/incoming'
    | '/inventory'
    | '/outgoing'
    | '/reports'
    | '/settings'
    | '/stock-movements'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/incoming'
    | '/inventory'
    | '/outgoing'
    | '/reports'
    | '/settings'
    | '/stock-movements'
    | '/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  IncomingRoute: typeof IncomingRoute
  InventoryRoute: typeof InventoryRoute
  OutgoingRoute: typeof OutgoingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StockMovementsRoute: typeof StockMovementsRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming': {
      id: '/incoming'
      path: '/incoming'
      fullPath: '/incoming'
      preLoaderRoute: typeof IncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outgoing': {
      id: '/outgoing'
      path: '/outgoing'
      fullPath: '/outgoing'
      preLoaderRoute: typeof OutgoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-movements': {
      id: '/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof StockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  IncomingRoute: IncomingRoute,
  InventoryRoute: InventoryRoute,
  OutgoingRoute: OutgoingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StockMovementsRoute: StockMovementsRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
